C     REAL PRECISION DEFINITION
      MODULE PRES
      INTEGER, PARAMETER :: P = SELECTED_REAL_KIND(6,37)
C     INTEGER, PARAMETER :: P = SELECTED_REAL_KIND(15,307)
C     INTEGER, PARAMETER :: P = SELECTED_REAL_KIND(33,4931)
      END MODULE
