C     REAL PRECISION DEFINITION
      MODULE PREC
      INTEGER, PARAMETER :: P = SELECTED_REAL_KIND(6,37)
c      INTEGER, PARAMETER :: P = SELECTED_REAL_KIND(15,307)
c      INTEGER, PARAMETER :: P = SELECTED_REAL_KIND(33,4931)
      END MODULE
